### ISSUE TITLE
[NEW-FEATURE] Diagrammi dei Moduli

### ISSUE THREAD

**Issue by AndreaGrandieri** [AndreaGrandieri/MagicMirror-GBM#131]
## Brief

**Descrizione richiesta**
Stesura Diagrammi dei Moduli.
Diagramma delle Classi incompatibile con un sistema a moduli. Convertito in Diagramma dei Moduli.

> In un sistema a moduli non si fa il diagramma delle classi tradizionale, ma un diagramma dei moduli che lo compongono

**Comment by giodabg** [comment]
In un sistema a moduli non si fa il diagramma delle classi tradizionale, ma un diagramma dei moduli che lo compongono

**Comment by AndreaGrandieri** [comment]
> In un sistema a moduli non si fa il diagramma delle classi tradizionale, ma un diagramma dei moduli che lo compongono

Ok, provvedo a convertire l'issue. @giodabg Qui tutto il riassunto del meeting di ieri: https://github.com/AndreaGrandieri/MagicMirror-GBM/pull/132

**Comment by manu2110** [comment]
https://www.uml-diagrams.org/component-diagrams.html

**Comment by AndreaGrandieri** [comment]
https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-component-diagram/

**Comment by AndreaGrandieri** [comment]
Seguite queste regole:


> https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-component-diagram/

gg
