### ISSUE TITLE
Struttura directory

### ISSUE THREAD

**Issue by giodabg** [AndreaGrandieri/MagicMirror-GBM#214]
Tutti i branch devono condividere la seguente struttura di directory:

- **Documentazione** (contenente tutta la documentazione ufficiale che verrà valutata dai prof e dall'azienda)
- **Prototipo.0.9** (contenente tutto il codice sorgente, il file Install.txt)
- **Archivio** (tutte le directory, i documenti, gli zip, ...  che non si utilizzano più)
- **doc**

Lo scopo di rinominare **src** dalla root a **Prototipo.0.9** è quello di testare tutti i collegamenti relativi/assoluti che sono presenti nel sistema.

Proposta di operazioni per la riorganizzazione:

- [x] Rilasciare **Release: `Prototipo.0.9`**
~rinominare **Documenti** in **Documentazione**~
- [x] ~rinominare **src** in  **Prototipo.0.9**~ ----> utilizzo delle **Release di GitHub** previsto
- [x] spostare **test**  in  ~**Prototipo.0.9** o in~ **Archivio**
- [x] spostare in Documenti **Versione Riserva Documento Modulo MMM-AVStock**, **Project Management\resources**, **Meetings Log**, "Moduli\outdated" ... e tutto quanto è inutile o è duplicato in **doc** in **Archivio**
- [x] ~ricopiare **Documenti\Moduli/IMPORTANTE-gestione-dir-implementazione-moduli.md** in **Prototipo.0.9** in formato testo/docx/...~ ----> il documento è ad uso interno. Pertanto è stato spostato in Archivio.
- [x] ~spostare **Documenti\Istruzione per Testing** in **Prototipo.0.9** in formato testo/docx/...~ ----> il documento è ad uso interno. Pertanto è stato spostato in **Archivio**. Pubblicamente riferire a https://andreagrandieri.github.io/MagicMirror-GBM/pages/MagicMirror-GBM-OS.html

Il **codice di prova/test** deve trovarsi sempre nella directory "**Prototipo.0.9**" all'interno del **proprio branch**.

Alla **fine della settimana** si procede con la sincronizzazione nel **main** in modo da ripartire il **lunedì** da una **situazione identica** per tutto il gruppo.

**Comment by AndreaGrandieri** [comment]
Chiusura prevista al rilascio della **Release: `Prototipo.0.9`**

**Comment by AndreaGrandieri** [comment]
https://github.com/AndreaGrandieri/MagicMirror-GBM/releases
Latest (al 05.01.2021 19:50 (mm/dd/yyyy)): https://github.com/AndreaGrandieri/MagicMirror-GBM/releases/tag/v1.3
